name: built_path_annotations
version: 0.2.0
description: >-
  Contains annotations for `package:built_path`.
  See that package for more information.
homepage: https://github.com/dnfield/flutter_built_path

environment:
  sdk: '>=2.18.1 <3.0.0'
  # flutter: ">=0.5.1 <2.0.0"
    
# dependencies:
  # flutter:
  #   sdk: flutter